name: Python CI for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ChromeDriver (Windows)
      run: |
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_win32.zip" -OutFile "chromedriver.zip"
        Expand-Archive -Path "chromedriver.zip" -DestinationPath "."
        if (-Not (Test-Path -Path "C:\chromedriver")) {
          New-Item -ItemType Directory -Path "C:\chromedriver"
        }
        Move-Item -Path ".\chromedriver.exe" -Destination "C:\chromedriver\chromedriver.exe"
        echo "chromedriver installed to C:\chromedriver"

    - name: Add ChromeDriver to PATH
      run: |
        setx PATH "$env:PATH;C:\chromedriver"
        echo "ChromeDriver added to PATH"

    - name: Set FLASK_APP environment variable
      run: |
        echo "FLASK_APP=appi.app" >> $GITHUB_ENV
        echo "FLASK_ENV=development" >> $GITHUB_ENV

    - name: Run Flask server
      run: |
        Start-Process -NoNewWindow -FilePath "python" -ArgumentList "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"

    - name: Run tests
      run: |
        python -m unittest discover tests
